CREATE EXTERNAL TABLE IF NOT EXISTS wnba_db.wnba_teambox_2018_22_raw (
    record_number STRING,
    game_id STRING,
    season STRING,
    season_type STRING,
    game_date STRING,
    game_date_time STRING,
    team_id STRING,
    team_uid STRING,
    team_slug STRING,
    team_location STRING,
    team_name STRING,
    team_abbreviation STRING,
    team_display_name STRING,
    team_short_display_name STRING,
    team_color STRING,
    team_alternate_color STRING,
    team_logo STRING,
    team_home_away STRING,
    team_score STRING,
    team_winner STRING,
    assists STRING,
    blocks STRING,
    defensive_rebounds STRING,
    field_goal_pct STRING,
    field_goals_made STRING,
    field_goals_attempted STRING,
    flagrant_fouls STRING,
    fouls STRING,
    free_throw_pct STRING,
    free_throws_made STRING,
    free_throws_attempted STRING,
    largest_lead STRING,
    offensive_rebounds STRING,
    steals STRING,
    team_turnovers STRING,
    technical_fouls STRING,
    three_point_field_goal_pct STRING,
    three_point_field_goals_made STRING,
    three_point_field_goals_attempted STRING,
    total_rebounds STRING,
    total_technical_fouls STRING,
    total_turnovers STRING,
    turnovers STRING,
    opponent_team_id STRING,
    opponent_team_uid STRING,
    opponent_team_slug STRING,
    opponent_team_location STRING,
    opponent_team_name STRING,
    opponent_team_abbreviation STRING,
    opponent_team_display_name STRING,
    opponent_team_short_display_name STRING,
    opponent_team_color STRING,
    opponent_team_alternate_color STRING,
    opponent_team_logo STRING,
    opponent_team_score STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    'separatorChar' = ',',
    'quoteChar' = '\"',
    'skip.header.line.count'='1'
)
LOCATION 's3://wnballmbucketar/team-box/2018-22/'
TBLPROPERTIES ('has_encrypted_data'='false');