CREATE EXTERNAL TABLE IF NOT EXISTS wnba_db.wnba_schedule_2024_raw (
    record_number STRING,
    id STRING,
    uid STRING,
    date1 STRING,
    attendance STRING,
    time_valid BOOLEAN,
    neutral_site BOOLEAN,
    conference_competition BOOLEAN,
    play_by_play_available BOOLEAN,
    recent BOOLEAN,
    start_date STRING,
    notes_type STRING,
    notes_headline STRING,
    broadcast_market STRING,
    broadcast_name STRING,
    type_id STRING,
    type_abbreviation STRING,
    venue_id STRING,
    venue_full_name STRING,
    venue_address_city STRING,
    venue_address_state STRING,
    venue_indoor BOOLEAN,
    status_clock STRING,
    status_display_clock STRING,
    status_period STRING,
    status_type_id STRING,
    status_type_name STRING,
    status_type_state STRING,
    status_type_completed BOOLEAN,
    status_type_description STRING,
    status_type_detail STRING,
    status_type_short_detail STRING,
    format_regulation_periods STRING,
    home_id STRING,
    home_uid STRING,
    home_location STRING,
    home_name STRING,
    home_abbreviation STRING,
    home_display_name STRING,
    home_short_display_name STRING,
    home_color STRING,
    home_alternate_color STRING,
    home_is_active BOOLEAN,
    home_venue_id STRING,
    home_logo STRING,
    home_score INT,
    home_winner BOOLEAN,
    home_linescores STRING,
    home_records STRING,
    away_id STRING,
    away_uid STRING,
    away_location STRING,
    away_name STRING,
    away_abbreviation STRING,
    away_display_name STRING,
    away_short_display_name STRING,
    away_color STRING,
    away_alternate_color STRING,
    away_is_active BOOLEAN,
    away_venue_id STRING,
    away_logo STRING,
    away_score INT,
    away_winner BOOLEAN,
    away_linescores STRING,
    away_records STRING,
    game_id STRING,
    season STRING,
    season_type STRING,
    status_type_alt_detail STRING,
    game_json STRING,
    game_json_url STRING,
    game_date_time STRING,
    game_date STRING,
    PBP BOOLEAN,
    team_box BOOLEAN,
    player_box BOOLEAN
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    'separatorChar' = ',',
    'quoteChar' = '\"'
)
LOCATION 's3://wnballmbucketar/schedule/2024/'
TBLPROPERTIES (
    'skip.header.line.count'='1',
    'has_encrypted_data'='false'
);