CREATE EXTERNAL TABLE IF NOT EXISTS wnba_db.wnba_player_box (
    record_number STRING,
    game_id BIGINT,
    season INT,
    season_type INT,
    game_date STRING,
    game_date_time STRING,
    athlete_id STRING,
    athlete_display_name STRING,
    team_id INT,
    team_name STRING,
    team_location STRING,
    team_short_display_name STRING,
    minutes STRING,
    field_goals_made STRING,
    field_goals_attempted STRING,
    three_point_field_goals_made STRING,
    three_point_field_goals_attempted STRING,
    free_throws_made STRING,
    free_throws_attempted STRING,
    offensive_rebounds STRING,
    defensive_rebounds STRING,
    rebounds STRING,
    assists STRING,
    steals STRING,
    blocks STRING,
    turnovers STRING,
    fouls STRING,
    plus_minus STRING,
    points STRING,
    starter BOOLEAN,
    ejected BOOLEAN,
    did_not_play BOOLEAN,
    reason STRING,
    active BOOLEAN,
    athlete_jersey STRING,
    athlete_short_name STRING,
    athlete_headshot_href STRING,
    athlete_position_name STRING,
    athlete_position_abbreviation STRING,
    team_display_name STRING,
    team_uid STRING,
    team_slug STRING,
    team_logo STRING,
    team_abbreviation STRING,
    team_color STRING,
    team_alternate_color STRING,
    home_away STRING,
    team_winner BOOLEAN,
    team_score INT,
    opponent_team_id STRING,
    opponent_team_name STRING,
    opponent_team_location STRING,
    opponent_team_display_name STRING,
    opponent_team_abbreviation STRING,
    opponent_team_logo STRING,
    opponent_team_color STRING,
    opponent_team_alternate_color STRING,
    opponent_team_score INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    'separatorChar' = ',',
    'quoteChar' = '\"'
)
LOCATION 's3://wnballmbucketar/player-box/'
TBLPROPERTIES (
    'skip.header.line.count'='1',
    'has_encrypted_data'='false'
);